export const API_TRANSACTION_BEGIN = 'API_TRANSACTION_BEGIN';
export const API_TRANSACTION_END = 'API_TRANSACTION_END';
export const API_TRANSACTION_ERROR = 'API_TRANSACTION_ERROR';
export const API_TRANSACTION_CANCEL = 'API_TRANSACTION_CANCEL';
