export const API_TRANSACTION_BEGIN = 'API_TRANSACTION_BEGIN';
export const API_TRANSACTION_END = 'API_TRANSACTION_END';
export const API_TRANSACTION_ERROR = 'API_TRANSACTION_ERROR';
export const API_TRANSACTION_CANCEL = 'API_TRANSACTION_CANCEL';
export const GET_BEERS = 'GET_BEERS';
export const GET_BEERS_FILTER = 'GET_BEERS_FILTER';
export const UPDATE_IDS = 'UPDATE_IDS';
